Initial Pull Request
lnls-fac/hlafac pull request #11
Opened 2020-11-18 21:12 UTC by fernandohds564

2020-11-18 21:19 UTC, anacso17 commented on Makefile
> +	sudo sed -i '/pyqt-apps/d' $(DISTPATH)/easy-install.pth
I think we do not need `pyqt-apps` here

2020-11-18 21:23 UTC, fernandohds564 commented on Makefile
> +	sudo sed -i '/pyqt-apps/d' $(DISTPATH)/easy-install.pth
right!
fixed!

2020-11-19 17:20 UTC, murilobalves approved these changes

2020-11-23 14:12 UTC, xresende approved these changes

2021-01-08 18:17 UTC, murilobalves approved these changes

2021-01-08 21:00 UTC, anacso17 approved these changes

2021-01-11 12:35 UTC, anacso17 approved these changes

2021-01-11 15:28 UTC, murilobalves requested changes

2021-01-11 15:28 UTC, murilobalves commented on siriushlafac/as_ap_trajfit/main.py
> +        wid.layout().addWidget(QLabel('\u03bd<sub>y</sub>', wid), 1, 0)
I think it is <sub>x</sub> here

2021-01-11 16:25 UTC, fernandohds564 commented on siriushlafac/as_ap_trajfit/main.py
> +        wid.layout().addWidget(QLabel('\u03bd<sub>y</sub>', wid), 1, 0)
right! Thanks!

2021-01-11 17:49 UTC, fernandohds564 commented on siriushlafac/as_ap_trajfit/main.py
> +        wid.layout().addWidget(QLabel('\u03bd<sub>y</sub>', wid), 1, 0)
done!

2021-01-11 17:52 UTC, murilobalves approved these changes

2021-01-11 19:25 UTC, xresende approved these changes

2021-01-12 11:40 UTC, merged